version: "3.4"

services:
  web:
    build:
      context: .
      target: builder
      args:
        API_URL: https://covid19sayac.xyz
    restart: unless-stopped
    ports:
      - 80:3000
    environment:
      NUXT_HOST: 0.0.0.0
      NUXT_PORT: 3000
  # web:
  #   image: nginx:alpine
  #   restart: unless-stopped
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./dist:/usr/share/nginx/html
